# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dff912587317a7cfebdb901786c434f00fef6d3ff4e214e7072f3e2bb1398f23daeba7ce34b15609ce26eab535e7875c5b2f7540646bb84fc9b2b0f4758ec57

test:
  secret_key_base: ab1eadebf5e8d9f5ce249cf321f508902ca7951c5e9b7a1b2c9b42645ea5571aaa89886e9fa84993f4b8c24c29134c0e9ffb9cbdd9fbf2904bb756a7c5b4d431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
